// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6jfbsUjrxixUEE-DQI8w4lLGiejx1-7E',
    appId: '1:1088823996414:web:169c66739a96bbe2599aaf',
    messagingSenderId: '1088823996414',
    projectId: 'mnac-1cda6',
    authDomain: 'mnac-1cda6.firebaseapp.com',
    storageBucket: 'mnac-1cda6.firebasestorage.app',
    measurementId: 'G-JVLL98MN1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY_MeYnIQa5W2lGNSA_j0ocnNVZSbEbFQ',
    appId: '1:1088823996414:android:9fc897549a981e53599aaf',
    messagingSenderId: '1088823996414',
    projectId: 'mnac-1cda6',
    storageBucket: 'mnac-1cda6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn9CToCoh2d36hLQ7KO8PnXQEKbXhIkvY',
    appId: '1:1088823996414:ios:56d2988957c165cb599aaf',
    messagingSenderId: '1088823996414',
    projectId: 'mnac-1cda6',
    storageBucket: 'mnac-1cda6.firebasestorage.app',
    iosBundleId: 'com.virabyan.mnac',
  );
}
